### ISSUE TITLE
urn:cts:greekLit:tlg5026.e3.hmt:17.E3_225v_3

### ISSUE THREAD

**Issue by Wieke98** [homermultitext/scholia-english#13]
Lemma (leave blank if no lemma): βοσκομένης ἀγέλης . Comparison of the killing by Menelaos of Euphorbos to a lion seizing a cow from a herd. 

Comment: He compares everything; the mass of the Trojans is compared to the whole herd; and Euphorbos being the best one is compared to the best <cow> of them. That he is the best one, the poet testifies: “after he had stood over Patroklos, he wounded the best of the Trojans:” (Hom. Il. 17.80) The killer Menelaos is compared to the lion, the inaction of the chief of the Trojans compares to herdsmen and dogs not being capable to defend <the herd>.

**Comment by Wieke98** [comment]
Translated with help from dr. T.A. van Berkel

**Comment by caseydue** [comment]
I think in the place that says "lemma" on this form you should just leave it blank, since there is no lemma at the start of the scholion in the manuscript. Also, I think it would be best to preserve the syntax of the scholion, with εἰκάζων being a nominative participle agreeing with the unstated "poet." So something like: He compares everything, likening the mass of the Trojans to the whole herd; and (likening) Euphorbos being the best one to the best of them... (He likens) the killer Menelaos to a lion, the inaction of the best Trojans to herdsmen and dogs not being capable to defend. If you agree with these changes could you comment and paste in a new, revised version of the translation of the whole comment? Thank you!!

**Comment by Wieke98** [comment]
Lemma: <Comparison of the killing by Menelaos of Euphorbos to a lion seizing a cow from a herd>.

Comment: He compares everything; likening the mass of the Trojans to the whole herd; and Euphorbos being the best one to the best of them. That he is the best one, the poet testifies: “after he had stood over Patroklos, he wounded the best of the Trojans:” (Hom. Il. 17.80) Likening the killer Menelaos to the lion, the inaction of the chief of the Trojans to herdsmen and dogs not being capable to defend.

**Comment by caseydue** [comment]
Lemma:

Comment: He compares everything; likening the mass of the Trojans to the whole herd; and Euphorbos being the best one to the best of them. That he is the best one, the poet testifies: “after he had stood over Patroklos, he wounded the best of the Trojans” (Hom. Il. 17.80). Likening the killer Menelaos to a lion, the inaction of the chiefs [= "those being the best"] of the Trojans to herdsmen and dogs not being capable to defend.

Translation by Wieke Snoeij and Tazuko van Berkel.
