### ISSUE TITLE
urn:cts:greekLit:tlg5026.e3.hmt:17.e3_224v_4

### ISSUE THREAD

**Issue by nadimattia** [homermultitext/scholia-english#14]
Lemma (leave blank if no lemma): δ

Comment: First he uses the leopard, for this animal is bold. Second he uses the lion, for with courage one also needs fighting spirit. Third, boar, not because it is more noble, but because it is carried along by unthinking assault, while the lions and leopards are on guard against suffering often; because of that he brought in "the spirit is the greatest." And differently (in other scholia), the lion and leopard are often tamed, but he (the boar) is always wild.

**Comment by caseydue** [comment]
Is there just one author for this scholion? If so, I think the URN should be: urn:cts:greekLit:tlg5026.e3.nadimattia:17.e3_224v_4

If multiple people worked on it, please add a comment here on this issue with the names of all translators. 

The translation is very good, but I think the adverb πολλάκις goes with the participle, so "while lions and leopards are often on guard against suffering." Also, perhaps instead of "differently" it should be "elsewhere"? 

Once you have had a chance to look at it again, you can comment here and submit in your comment a revised translation of the whole note. Thank you!

**Comment by nadimattia** [comment]
Translators: Natalie DiMattia, Abigail Smith, Leonie Henkes

**Comment by nadimattia** [comment]
Lemma (leave blank if no lemma): δ

Comment: First he uses the leopard, for this animal is bold. Second he uses the lion, for with courage one also needs fighting spirit. Third, boar, not because it is more noble, but because it is carried along by unthinking assault, while the lions and leopards are often on guard against suffering; because of that he brought in "the spirit is the greatest." And elsewhere, the lion and leopard are often tamed, but he (the boar) is always wild.

**Comment by caseydue** [comment]
This looks great, I am closing it! Thank you so much!
